name: Run tests upon merging to main

on:
  pull_request:
    branches: [ "main" ]
    types: [closed] # This ensures the workflow runs when the PR is merged
    paths:
      - 'tests/**' # This ensures the workflow runs only when files in the 'tests' folder are changed
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run tests
